[tool.poetry]
name = "mops"
version = "0.1.0"
description = ""
authors = ["Yan Ma <yanma23@m.fudan.edu.cn>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
